// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: person.proto

package person

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Image                []byte   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ProfileVerified      bool     `protobuf:"varint,5,opt,name=profile_verified,json=profileVerified,proto3" json:"profile_verified,omitempty"`
	Height               float32  `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Person) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Person) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Person) GetProfileVerified() bool {
	if m != nil {
		return m.ProfileVerified
	}
	return false
}

func (m *Person) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Person)(nil), "person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x41, 0xca, 0x83, 0x30,
	0x10, 0x46, 0x19, 0xfd, 0x0d, 0x3a, 0x08, 0xbf, 0x84, 0x52, 0x42, 0xe9, 0x22, 0x74, 0x95, 0x6e,
	0xba, 0xe9, 0x4d, 0xb2, 0xe8, 0xb6, 0x58, 0x3a, 0xea, 0x80, 0x1a, 0x89, 0xa1, 0xb7, 0xea, 0x1d,
	0x8b, 0x1a, 0xda, 0xdd, 0xbc, 0xf7, 0x60, 0xf8, 0xb0, 0x9c, 0xc8, 0xcf, 0x6e, 0xbc, 0x4c, 0xde,
	0x05, 0x77, 0x7a, 0x03, 0x8a, 0x4d, 0xc8, 0x0a, 0xd3, 0xba, 0x25, 0x05, 0x1a, 0x4c, 0x66, 0x97,
	0x53, 0x1e, 0xb1, 0x68, 0xd8, 0xcf, 0x61, 0xac, 0x07, 0x52, 0x89, 0x06, 0x53, 0xd8, 0x9f, 0x90,
	0x07, 0xcc, 0xfb, 0x3a, 0xc6, 0x74, 0x8d, 0x5f, 0x96, 0x3b, 0xcc, 0x78, 0x58, 0xbe, 0xfd, 0x69,
	0x30, 0xa5, 0xdd, 0x40, 0x9e, 0xb1, 0x9a, 0xbc, 0x6b, 0xb8, 0xa7, 0xfb, 0x8b, 0x3c, 0x37, 0x4c,
	0x4f, 0x95, 0x69, 0x30, 0xb9, 0xfd, 0x8f, 0xfe, 0x16, 0xb5, 0xdc, 0xa3, 0xe8, 0x88, 0xdb, 0x2e,
	0x28, 0xa1, 0xc1, 0x24, 0x36, 0xd2, 0x43, 0xac, 0xb3, 0xaf, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x38, 0x9b, 0x1b, 0x06, 0xc6, 0x00, 0x00, 0x00,
}
