// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: repeated_fields.proto

package repeated_fields

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Image                []byte   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ProfileVerified      bool     `protobuf:"varint,5,opt,name=profile_verified,json=profileVerified,proto3" json:"profile_verified,omitempty"`
	Height               float32  `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	PhoneNo              []string `protobuf:"bytes,7,rep,name=phone_no,json=phoneNo,proto3" json:"phone_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_458f09428f4fd496, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Person) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Person) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Person) GetProfileVerified() bool {
	if m != nil {
		return m.ProfileVerified
	}
	return false
}

func (m *Person) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Person) GetPhoneNo() []string {
	if m != nil {
		return m.PhoneNo
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "person")
}

func init() { proto.RegisterFile("repeated_fields.proto", fileDescriptor_458f09428f4fd496) }

var fileDescriptor_458f09428f4fd496 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x86, 0x91, 0x5d, 0xcb, 0xf6, 0x51, 0xa8, 0x11, 0x6d, 0x51, 0x4b, 0x07, 0xd1, 0x49, 0x5d,
	0xba, 0xe4, 0x3d, 0x32, 0x68, 0xc8, 0x6a, 0x14, 0x7c, 0xb2, 0x05, 0xb6, 0x24, 0x64, 0x91, 0x67,
	0xcc, 0x63, 0x05, 0x3b, 0x22, 0xd9, 0xee, 0xfb, 0x3e, 0x38, 0xf8, 0xe1, 0x23, 0x62, 0x40, 0x9d,
	0x70, 0xe8, 0x8d, 0xc5, 0x79, 0x58, 0xff, 0x43, 0xf4, 0xc9, 0xff, 0x5e, 0x09, 0xd0, 0x80, 0x71,
	0xf5, 0x8e, 0x75, 0x50, 0xea, 0x11, 0x39, 0x11, 0x44, 0x56, 0x6a, 0x3b, 0xd9, 0x0f, 0xb4, 0xc6,
	0xc6, 0x35, 0x39, 0xbd, 0x20, 0x2f, 0x04, 0x91, 0xad, 0x7a, 0x0a, 0xf6, 0x0d, 0xcd, 0xac, 0x73,
	0x2c, 0xf7, 0xf8, 0x60, 0xf6, 0x0e, 0x95, 0x5d, 0xb6, 0x6f, 0x2f, 0x82, 0xc8, 0x57, 0x75, 0x07,
	0xf6, 0x07, 0x5d, 0x88, 0xde, 0xd8, 0x19, 0xfb, 0x0b, 0x46, 0x6b, 0x2c, 0x0e, 0xbc, 0x12, 0x44,
	0x36, 0xea, 0x2d, 0xfb, 0x53, 0xd6, 0xec, 0x13, 0xe8, 0x84, 0x76, 0x9c, 0x12, 0xa7, 0x82, 0xc8,
	0x42, 0x65, 0x62, 0x5f, 0xd0, 0x84, 0xc9, 0x3b, 0xec, 0x9d, 0xe7, 0xb5, 0x28, 0x65, 0xab, 0xea,
	0x9d, 0x8f, 0xfe, 0x4c, 0xf7, 0x45, 0x87, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x4a, 0x71,
	0xce, 0xea, 0x00, 0x00, 0x00,
}
